"""add ai analysis fields and resume job match

Revision ID: 1e575f30f579
Revises: e463465a6013
Create Date: 2026-08-30 17:47:15.031738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e575f30f579'
down_revision: Union[str, None] = 'e463465a6013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_job_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=False),
    sa.Column('overall_match_score', sa.Integer(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('strengths', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_job_matches_job_description_id'), 'resume_job_matches', ['job_description_id'], unique=False)
    op.create_index(op.f('ix_resume_job_matches_resume_id'), 'resume_job_matches', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_job_matches_user_id'), 'resume_job_matches', ['user_id'], unique=False)
    op.add_column('interview_questions', sa.Column('difficulty', sa.String(length=20), server_default=sa.text("'medium'"), nullable=False))
    op.add_column('interview_questions', sa.Column('topic', sa.String(length=255), nullable=True))
    op.add_column('interview_questions', sa.Column('expected_focus', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('difficulty', sa.String(length=20), server_default=sa.text("'medium'"), nullable=False))
    op.add_column('interviews', sa.Column('question_count', sa.Integer(), server_default=sa.text('5'), nullable=False))
    op.add_column('interviews', sa.Column('duration', sa.Integer(), server_default=sa.text('30'), nullable=False))
    op.add_column('interviews', sa.Column('question_types', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('job_descriptions', sa.Column('analysis', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('resumes', sa.Column('analysis', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'analysis')
    op.drop_column('job_descriptions', 'analysis')
    op.drop_column('interviews', 'question_types')
    op.drop_column('interviews', 'duration')
    op.drop_column('interviews', 'question_count')
    op.drop_column('interviews', 'difficulty')
    op.drop_column('interview_questions', 'expected_focus')
    op.drop_column('interview_questions', 'topic')
    op.drop_column('interview_questions', 'difficulty')
    op.drop_index(op.f('ix_resume_job_matches_user_id'), table_name='resume_job_matches')
    op.drop_index(op.f('ix_resume_job_matches_resume_id'), table_name='resume_job_matches')
    op.drop_index(op.f('ix_resume_job_matches_job_description_id'), table_name='resume_job_matches')
    op.drop_table('resume_job_matches')
    # ### end Alembic commands ###
