"""add answer evaluations follow ups and report fields

Revision ID: a4a8da0feaed
Revises: 1e575f30f579
Create Date: 2026-09-06 13:18:17.655024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a8da0feaed'
down_revision: Union[str, None] = '1e575f30f579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_answers', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('interview_answers', sa.Column('evaluation', sa.JSON(), nullable=True))
    op.add_column('interview_answers', sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interview_questions', sa.Column('parent_question_id', sa.UUID(), nullable=True))
    op.add_column('interview_questions', sa.Column('is_follow_up', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('interview_questions', sa.Column('follow_up_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_interview_questions_parent_question_id'), 'interview_questions', ['parent_question_id'], unique=False)
    op.create_foreign_key(None, 'interview_questions', 'interview_questions', ['parent_question_id'], ['id'], ondelete='CASCADE')
    op.add_column('interview_results', sa.Column('technical_score', sa.Float(), nullable=True))
    op.add_column('interview_results', sa.Column('communication_score', sa.Float(), nullable=True))
    op.add_column('interview_results', sa.Column('relevance_score', sa.Float(), nullable=True))
    op.add_column('interview_results', sa.Column('problem_solving_score', sa.Float(), nullable=True))
    op.add_column('interview_results', sa.Column('resume_alignment', sa.Text(), nullable=True))
    op.add_column('interview_results', sa.Column('missing_skills', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('interview_results', sa.Column('suggestions', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('interview_results', sa.Column('preparation_topics', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('interview_results', sa.Column('question_results', sa.JSON(), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('interview_results', sa.Column('completion_summary', sa.Text(), nullable=True))
    op.add_column('interview_results', sa.Column('overall_feedback', sa.Text(), nullable=True))
    op.add_column('interview_results', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('interview_results', sa.Column('uncertainty_notes', sa.Text(), nullable=True))
    op.add_column('interviews', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'completed_at')
    op.drop_column('interview_results', 'uncertainty_notes')
    op.drop_column('interview_results', 'confidence')
    op.drop_column('interview_results', 'overall_feedback')
    op.drop_column('interview_results', 'completion_summary')
    op.drop_column('interview_results', 'question_results')
    op.drop_column('interview_results', 'preparation_topics')
    op.drop_column('interview_results', 'suggestions')
    op.drop_column('interview_results', 'missing_skills')
    op.drop_column('interview_results', 'resume_alignment')
    op.drop_column('interview_results', 'problem_solving_score')
    op.drop_column('interview_results', 'relevance_score')
    op.drop_column('interview_results', 'communication_score')
    op.drop_column('interview_results', 'technical_score')
    op.drop_constraint(None, 'interview_questions', type_='foreignkey')
    op.drop_index(op.f('ix_interview_questions_parent_question_id'), table_name='interview_questions')
    op.drop_column('interview_questions', 'follow_up_reason')
    op.drop_column('interview_questions', 'is_follow_up')
    op.drop_column('interview_questions', 'parent_question_id')
    op.drop_column('interview_answers', 'evaluated_at')
    op.drop_column('interview_answers', 'evaluation')
    op.drop_column('interview_answers', 'score')
    # ### end Alembic commands ###
