"""add unique constraint on interview answers

Revision ID: dab4f1eabb4c
Revises: a4a8da0feaed
Create Date: 2026-09-07 22:23:30.242816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab4f1eabb4c'
down_revision: Union[str, None] = 'a4a8da0feaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_interview_answers_interview_question', 'interview_answers', ['interview_id', 'question_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_interview_answers_interview_question', 'interview_answers', type_='unique')
    # ### end Alembic commands ###
